#!/bin/bash

if [ ! -f "./Cargo.toml" ]; then
  echo "error: run this script in the lemon project directory."
  exit 1
fi


if [ "$1" = "-d" ] || [ "$1" = "dev" ]; then
  shift
  cargo run -- "$@"
  exit $?
fi

if [ "$1" = "-r" ] || [ "$1" = "build" ]; then
  shift
  cargo build --release "$@"
  exit $?
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "usage: lemon [-d] [-r] [...]"
  echo "  -d: run in debug mode"
  echo "  -r: run in release mode"
  exit 0
fi

if [ ! -f "./target/release/lemon" ]; then
  echo "error: release binary not found. please run 'cargo build --release'."
  exit 1
fi
./target/release/lemon "$@"
