#!/bin/bash

if [ ! -f "./Cargo.toml" ]; then
  echo "you can't run lemon outside of lemon directory"
  exit 1
fi
# if [ "$1" = "build" ] || [ "$1" = "-b" ]; then
#   cargo build --release
#   exit 0
# fi

if [ ! -f "./target/release/lemon" ]; then
  echo "lemon bin not found, try run 'cargo build --release'"
  # cargo build --release
fi
# if [[ $(git status --porcelain) ]]; then
#   echo "build with changes..."
#    cargo build --release
# fi
./target/release/lemon "$@"
