mod synthesise_ast_type;
mod synthesise_extern_fn_stmt;
mod synthesise_fn_stmt;
mod synthesise_literal;
mod synthesise_type_def_stmt;
pub(crate) use synthesise_ast_type::*;
pub(crate) use synthesise_extern_fn_stmt::*;
pub(crate) use synthesise_fn_stmt::*;
pub(crate) use synthesise_literal::*;
pub(crate) use synthesise_type_def_stmt::*;
